name: Issue
description: Add issue
body:
  - type: markdown
    attributes:
      value: |
        ## 背景・概要

        ## 目的

        ## やること

        - [ ] infra
        - [ ] api
        - [ ] front

name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 背景・概要


        ## 目的

        ## やること

        - [ ] infra
        - [ ] api
        - [ ] front
