/* eslint-disable */
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** An ISO 8601-encoded date */
  ISO8601Date: { input: any; output: any; }
};

/** Autogenerated input type of CreateRider */
export type CreateRiderInput = {
  /** 生年月日 */
  birthday: Scalars['ISO8601Date']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** 姓 */
  familyName: Scalars['String']['input'];
  /** 名 */
  givenName: Scalars['String']['input'];
  /** 国籍 */
  nationality: Scalars['String']['input'];
};

/** Autogenerated return type of CreateRider. */
export type CreateRiderPayload = {
  __typename?: 'CreateRiderPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  /** エラー内容 */
  errors: Array<Scalars['String']['output']>;
  /** ライダー */
  rider?: Maybe<Rider>;
};

export type Mutation = {
  __typename?: 'Mutation';
  /** ライダーを作成します */
  createRider?: Maybe<CreateRiderPayload>;
  /** ライダーを更新します */
  updateRider?: Maybe<UpdateRiderPayload>;
};


export type MutationCreateRiderArgs = {
  input: CreateRiderInput;
};


export type MutationUpdateRiderArgs = {
  input: UpdateRiderInput;
};

export type Query = {
  __typename?: 'Query';
  /** 指定IDのライダーを返します */
  rider: Rider;
  /** ライダーリストを返します */
  riders?: Maybe<Array<Rider>>;
};


export type QueryRiderArgs = {
  id: Scalars['ID']['input'];
};

/** ライダー */
export type Rider = {
  __typename?: 'Rider';
  /** 年齢 */
  age?: Maybe<Scalars['Int']['output']>;
  /** 生年月日 */
  birthday?: Maybe<Scalars['ISO8601Date']['output']>;
  /** 姓 */
  familyName?: Maybe<Scalars['String']['output']>;
  /** 氏名 */
  fullName?: Maybe<Scalars['String']['output']>;
  /** 名 */
  givenName?: Maybe<Scalars['String']['output']>;
  /** ID */
  id: Scalars['ID']['output'];
  /** 国籍 */
  nationality?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of UpdateRider */
export type UpdateRiderInput = {
  /** 生年月日 */
  birthday: Scalars['ISO8601Date']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** 姓 */
  familyName: Scalars['String']['input'];
  /** 名 */
  givenName: Scalars['String']['input'];
  /** ID */
  id: Scalars['ID']['input'];
  /** 国籍 */
  nationality: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateRider. */
export type UpdateRiderPayload = {
  __typename?: 'UpdateRiderPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  /** エラー内容 */
  errors: Array<Scalars['String']['output']>;
  /** ライダー */
  rider?: Maybe<Rider>;
};

export type UpdateRiderMutationVariables = Exact<{
  input: UpdateRiderInput;
}>;


export type UpdateRiderMutation = { __typename?: 'Mutation', updateRider?: { __typename?: 'UpdateRiderPayload', errors: Array<string>, rider?: { __typename?: 'Rider', id: string, fullName?: string | null, nationality?: string | null, birthday?: any | null, age?: number | null } | null } | null };

export type GetRiderQueryVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type GetRiderQuery = { __typename?: 'Query', rider: { __typename?: 'Rider', id: string, fullName?: string | null, familyName?: string | null, givenName?: string | null, nationality?: string | null, birthday?: any | null, age?: number | null } };

export type GetRidersQueryVariables = Exact<{ [key: string]: never; }>;


export type GetRidersQuery = { __typename?: 'Query', riders?: Array<{ __typename?: 'Rider', id: string, fullName?: string | null, nationality?: string | null, birthday?: any | null, age?: number | null }> | null };


export const UpdateRiderDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"updateRider"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UpdateRiderInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateRider"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"rider"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"nationality"}},{"kind":"Field","name":{"kind":"Name","value":"birthday"}},{"kind":"Field","name":{"kind":"Name","value":"age"}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"}}]}}]}}]} as unknown as DocumentNode<UpdateRiderMutation, UpdateRiderMutationVariables>;
export const GetRiderDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"getRider"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"rider"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"familyName"}},{"kind":"Field","name":{"kind":"Name","value":"givenName"}},{"kind":"Field","name":{"kind":"Name","value":"nationality"}},{"kind":"Field","name":{"kind":"Name","value":"birthday"}},{"kind":"Field","name":{"kind":"Name","value":"age"}}]}}]}}]} as unknown as DocumentNode<GetRiderQuery, GetRiderQueryVariables>;
export const GetRidersDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"getRiders"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"riders"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"nationality"}},{"kind":"Field","name":{"kind":"Name","value":"birthday"}},{"kind":"Field","name":{"kind":"Name","value":"age"}}]}}]}}]} as unknown as DocumentNode<GetRidersQuery, GetRidersQueryVariables>;